import type { Child } from '../domain/child.js';

export const fixtureChildren: Child[] = [
  {
    id: 'c001',
    nome: 'Ana Clara Mendes',
    data_nascimento: '2020-03-15',
    bairro: 'Rocinha',
    responsavel: 'Maria Mendes',
    saude: { ultima_consulta: '2025-11-10', vacinas_em_dia: true, alertas: [] },
    educacao: {
      escola: 'CIEP 305 Guilherme Bryan',
      frequencia_percent: 61,
      alertas: ['frequencia_baixa'],
    },
    assistencia_social: { cad_unico: true, beneficio_ativo: true, alertas: [] },
    revisado: false,
    revisado_por: null,
    revisado_em: null,
  },
  {
    id: 'c002',
    nome: 'Lucas Santos',
    data_nascimento: '2019-07-22',
    bairro: 'Maré',
    responsavel: 'Joana Santos',
    saude: {
      ultima_consulta: '2024-04-03',
      vacinas_em_dia: false,
      alertas: ['vacinas_atrasadas', 'consulta_atrasada'],
    },
    educacao: { escola: 'EM Professora Elzita', frequencia_percent: 88, alertas: [] },
    assistencia_social: {
      cad_unico: true,
      beneficio_ativo: false,
      alertas: ['beneficio_suspenso'],
    },
    revisado: false,
    revisado_por: null,
    revisado_em: null,
  },
  {
    id: 'c003',
    nome: 'Sofia Lima',
    data_nascimento: '2021-11-08',
    bairro: 'Rocinha',
    responsavel: 'Fernanda Carvalho',
    saude: { ultima_consulta: '2026-01-22', vacinas_em_dia: true, alertas: [] },
    educacao: null,
    assistencia_social: {
      cad_unico: false,
      beneficio_ativo: false,
      alertas: ['cadastro_ausente'],
    },
    revisado: true,
    revisado_por: 'a@b.test',
    revisado_em: '2026-02-10T09:14:00Z',
  },
  {
    id: 'c004',
    nome: 'Amanda Torres',
    data_nascimento: '2021-03-28',
    bairro: 'Mangueira',
    responsavel: 'Mônica Torres',
    saude: null,
    educacao: null,
    assistencia_social: null,
    revisado: false,
    revisado_por: null,
    revisado_em: null,
  },
  {
    id: 'c005',
    nome: 'Pedro Henrique',
    data_nascimento: '2018-08-14',
    bairro: 'Mangueira',
    responsavel: 'Cristina Araújo',
    saude: { ultima_consulta: '2026-03-10', vacinas_em_dia: true, alertas: [] },
    educacao: { escola: 'EM Silveira', frequencia_percent: 93, alertas: [] },
    assistencia_social: { cad_unico: true, beneficio_ativo: true, alertas: [] },
    revisado: false,
    revisado_por: null,
    revisado_em: null,
  },
];
