/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica o técnico e retorna um JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token: string;
                            /** @enum {string} */
                            token_type: "Bearer";
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista crianças com filtros, ordenação e paginação */
        get: {
            parameters: {
                query?: {
                    nome?: string;
                    bairro?: string;
                    alertas?: "com" | "sem" | "saude" | "educacao" | "assistencia_social";
                    revisado?: "true" | "false";
                    orderBy?: "nome" | "bairro" | "idade" | "alertas" | "revisao";
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                nome: string;
                                data_nascimento: string;
                                bairro: string;
                                responsavel: string;
                                saude: {
                                    ultima_consulta: string | null;
                                    vacinas_em_dia: boolean;
                                    alertas: ("vacinas_atrasadas" | "consulta_atrasada")[];
                                } | null;
                                educacao: {
                                    escola: string | null;
                                    frequencia_percent: number | null;
                                    alertas: ("frequencia_baixa" | "matricula_pendente")[];
                                } | null;
                                assistencia_social: {
                                    cad_unico: boolean;
                                    beneficio_ativo: boolean;
                                    alertas: ("cadastro_ausente" | "cadastro_desatualizado" | "beneficio_suspenso")[];
                                } | null;
                                revisado: boolean;
                                /** Format: email */
                                revisado_por: string | null;
                                /** Format: date-time */
                                revisado_em: string | null;
                                /** @enum {string} */
                                prioridade: "critico" | "atencao" | "monitorar" | "sem_dados" | "ok";
                                total_alertas: number;
                            }[];
                            pagination: {
                                page: number;
                                pageSize: number;
                                total: number;
                                totalPages: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os bairros distintos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bairros: string[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe completo de uma criança */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            nome: string;
                            data_nascimento: string;
                            bairro: string;
                            responsavel: string;
                            saude: {
                                ultima_consulta: string | null;
                                vacinas_em_dia: boolean;
                                alertas: ("vacinas_atrasadas" | "consulta_atrasada")[];
                            } | null;
                            educacao: {
                                escola: string | null;
                                frequencia_percent: number | null;
                                alertas: ("frequencia_baixa" | "matricula_pendente")[];
                            } | null;
                            assistencia_social: {
                                cad_unico: boolean;
                                beneficio_ativo: boolean;
                                alertas: ("cadastro_ausente" | "cadastro_desatualizado" | "beneficio_suspenso")[];
                            } | null;
                            revisado: boolean;
                            /** Format: email */
                            revisado_por: string | null;
                            /** Format: date-time */
                            revisado_em: string | null;
                            /** @enum {string} */
                            prioridade: "critico" | "atencao" | "monitorar" | "sem_dados" | "ok";
                            total_alertas: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desfaz a revisão de um caso */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            nome: string;
                            data_nascimento: string;
                            bairro: string;
                            responsavel: string;
                            saude: {
                                ultima_consulta: string | null;
                                vacinas_em_dia: boolean;
                                alertas: ("vacinas_atrasadas" | "consulta_atrasada")[];
                            } | null;
                            educacao: {
                                escola: string | null;
                                frequencia_percent: number | null;
                                alertas: ("frequencia_baixa" | "matricula_pendente")[];
                            } | null;
                            assistencia_social: {
                                cad_unico: boolean;
                                beneficio_ativo: boolean;
                                alertas: ("cadastro_ausente" | "cadastro_desatualizado" | "beneficio_suspenso")[];
                            } | null;
                            revisado: boolean;
                            /** Format: email */
                            revisado_por: string | null;
                            /** Format: date-time */
                            revisado_em: string | null;
                            /** @enum {string} */
                            prioridade: "critico" | "atencao" | "monitorar" | "sem_dados" | "ok";
                            total_alertas: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Registra que o técnico autenticado revisou o caso */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            nome: string;
                            data_nascimento: string;
                            bairro: string;
                            responsavel: string;
                            saude: {
                                ultima_consulta: string | null;
                                vacinas_em_dia: boolean;
                                alertas: ("vacinas_atrasadas" | "consulta_atrasada")[];
                            } | null;
                            educacao: {
                                escola: string | null;
                                frequencia_percent: number | null;
                                alertas: ("frequencia_baixa" | "matricula_pendente")[];
                            } | null;
                            assistencia_social: {
                                cad_unico: boolean;
                                beneficio_ativo: boolean;
                                alertas: ("cadastro_ausente" | "cadastro_desatualizado" | "beneficio_suspenso")[];
                            } | null;
                            revisado: boolean;
                            /** Format: email */
                            revisado_por: string | null;
                            /** Format: date-time */
                            revisado_em: string | null;
                            /** @enum {string} */
                            prioridade: "critico" | "atencao" | "monitorar" | "sem_dados" | "ok";
                            total_alertas: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores agregados do painel */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_criancas: number;
                            com_alertas: number;
                            sem_alertas: number;
                            sem_dados: number;
                            revisadas: number;
                            pendentes_revisao: number;
                            alertas_por_area: {
                                saude: number;
                                educacao: number;
                                assistencia_social: number;
                            };
                            por_bairro: {
                                bairro: string;
                                total: number;
                                com_alertas: number;
                                sem_dados: number;
                            }[];
                            cobertura: {
                                com_saude: number;
                                com_educacao: number;
                                com_assistencia_social: number;
                                sem_nenhuma_area: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
